// English copy for the Korean source portfolio and interface.
const english: Record<string, string> = {
  "궁금한 건 많고,": "Always curious,",
  "만드는 건 좋아해요.": "happiest building.",
  "수의학도이자 개발자, 범시우입니다": "I’m Siu, a vet student who builds things.",
  "수의학을 공부하며 AI와 소프트웨어를 만들어요.": "I study veterinary medicine and build AI and software.",
  "현장에서 발견한 질문을 연구하고, 실제로 쓰이는 도구로 옮깁니다.": "I turn questions from clinical practice into research and tools people use.",
  "제가 만든 것들": "Things I’ve built",
  "배우고, 만들고, 또 궁금해하고.": "Learn. Build. Stay curious.",
  "범시우": "Siu Beom",
  "본문으로 건너뛰기": "Skip to content",
  "Siu Beom 홈": "Siu Beom home",
  "주요 메뉴": "Main navigation",
  "호기심 많은 민트색 캐릭터와 수의학, AI, 개발 스티커": "A curious mint-colored character with veterinary medicine, AI, and coding stickers",
  "범시우 프로필 사진": "Portrait of Siu Beom",
  "프로젝트로 이동": "Go to projects",
  "포트폴리오 목차": "Portfolio contents",
  "현장의 문제에서 시작한 프로젝트": "Projects inspired by real-world problems",
  "임상 데이터에서 찾는 새로운 가능성": "Finding possibilities in clinical data",
  "질문을 연구로, 연구를 기록으로": "Questions, research, and things worth sharing",
  "작은 불편을 해결하는 도구들": "Small tools for everyday friction",
  "아이디어가 실제 사용 경험이 되기까지": "From an idea to something you can use",
  "배우고, 만들고, 함께한 시간": "Learning, building, and working together",
  "도전하며 쌓아온 경험": "A few milestones along the way",
  "임상 환자": "Canine patients",
  "사용 중인 수의 의료진": "Veterinary professionals using Vet-Sync",
  "프로젝트 자세히 보기": "More about this project",
  "연구 흐름도": "Research workflow",
  "ROC-AUC 비교 그래프": "ROC-AUC comparison chart",
  "학회 포스터": "Conference poster",
  "저를 소개합니다": "A little about me",
  "건국대학교 수의학과 재학": "Veterinary medicine student, Konkuk University",
  "이순신 교수님 연구실 학부연구생": "Undergraduate researcher in Prof. Sun-shin Yi’s lab",
  "벳츄원(VetU1) Vision AI / Software Developer": "Vision AI / Software Developer at VetU1",
  "재밌는 이야기, 환영해요!": "Got something fun in mind?",
  "2026.01 ~  AI Rookie 100팀 → 40팀 → 진행 중": "Jan 2026 – present · AI Rookie: 100 teams → 40 teams → Ongoing",
  "개 뇌전증 환자의 발작 기록 사각지대를 줄이기 위해 실제 임상 영상만으로 발작 후보 구간을 찾는 Vision AI를 연구하고 있습니다.": "I research vision AI that identifies potential seizure episodes in clinical videos, helping reduce gaps in seizure records for dogs with epilepsy.",
  "2026.10.05 · 시그니처동물의료센터에서 실사용 테스트 시작": "Oct 5, 2026 · Started real-world testing at Signature Animal Medical Center",
  "시그니처동물의료센터 임상 영상 42마리 · 350 clips": "350 clinical video clips from 42 dogs at Signature Animal Medical Center",
  "수의사 지도 아래 직접 구간 분리·라벨링": "Personally segmented and labeled videos under veterinary supervision",
  "개체 단위 데이터 분리로 처음 보는 환자에 대한 일반화 검증": "Used patient-level data splits to evaluate generalization to unseen dogs",
  "수의사의 판단 기준을 24개 임상 질문으로 구조화해 VLM 특징으로 활용": "Structured veterinary assessment criteria into 24 clinical questions to extract VLM features",
  "임상지식 기반 표현 ROC-AUC 0.865, 사전학습 영상 표현 0.771": "Clinical knowledge-based representations achieved ROC-AUC 0.865, versus 0.771 for pretrained video representations",
  "위치정보 baseline, 병실 배경, 의료진 개입에 따른 수집 편향 검증": "Evaluated a location-based baseline and collection bias from hospital backgrounds and staff intervention",
  "민감도 79%, Precision 0.39의 한계를 확인해 자동 경보보다 장시간 영상의 검토 후보 추출을 우선 활용 시나리오로 설정": "With 79% sensitivity and 0.39 precision, prioritized flagging segments for review in long videos rather than automated alerts",
  "Role · 문제 정의, 데이터 구축/라벨링, 모델 설계 및 실험, 오류 분석, 제1저자 논문 작성": "Role · Problem definition, dataset creation and labeling, model design and experiments, error analysis, and first-author manuscript preparation",
  "2026.01 ~ | Frontend Lead · Vision AI / Software Developer · 2026.07 정규직 전환": "Jan 2026 – present | Frontend Lead · Vision AI / Software Developer · Transitioned to full-time in Jul 2026",
  "459명의 수의 의료진이 사용하는 입원환자 관리 시스템입니다. 웨스턴 동물병원, VIP 동물병원 등 국내 대형 동물병원에서 사용 중인 VetSync의 프론트엔드 개발을 리드하고 있습니다. VetU1의 세 번째 초기 멤버로 합류했습니다.": "An inpatient management system used by 459 veterinary professionals. I lead frontend development for VetSync, used at major animal hospitals in Korea including Western Animal Hospital and VIP Animal Hospital. I joined VetU1 as its third early member.",
  "실제 의료진이 사용하는 입원환자 관리 기능 개발 및 개선": "Develop and improve inpatient management features used by clinical staff",
  "Vision AI 연구 결과를 병원 workflow에 연결하는 제품화 검토": "Explore bringing vision AI research into hospital workflows",
  "의료진의 업무 흐름과 데이터 구조를 이해한 뒤 기능 요구사항을 소프트웨어로 구현": "Translate clinical workflows, data structures, and feature requirements into working software",
  "확인해보기 👇": "Take a look ↓",
  "서비스 바로가기": "Visit Vet-Sync",
  "AI agent와 Python에서 HWPX 문서를 안정적으로 생성·편집·검증할 수 있도록 만든 오픈소스 도구입니다.": "An open-source tool for reliably creating, editing, and validating HWPX documents with AI agents and Python.",
  "HWPX 생성, 수정, 배포 양식 자동 채우기": "Create and edit HWPX documents and automatically fill existing forms",
  "중첩 표, 병합 셀, 형광펜, 이미지 등 실제 한국 문서 서식 지원": "Support Korean document layouts, including nested tables, merged cells, highlights, and images",
  "PNG/PDF 렌더링 및 레이아웃 검사": "Render to PNG/PDF and inspect layouts",
  "HWP ↔ HWPX 변환 workflow": "HWP ↔ HWPX conversion workflows",
  "확인한 것과 확인하지 못한 것을 분리해 보고하는 검증 설계": "Validation reports that distinguish verified results from unverified ones",
  "2026.01 ~": "Jan 2026 – present",
  "혈액 biomarker를 이용한 Canine Cognitive Dysfunction Syndrome(CCDS) 진단 보조 모델의 기존 성능과 평가 방법을 재검토했습니다.": "Reassessed the reported performance and evaluation methods of a blood biomarker-based model supporting canine cognitive dysfunction syndrome (CCDS) diagnosis.",
  "(NORMAL vs CCDS) 기존 Random Forest의 Accuracy 0.8877이 bootstrap 과정의 train/test 중복으로 과대평가된 것을 확인했습니다.": "(NORMAL vs CCDS) Identified that the existing Random Forest accuracy of 0.8877 was inflated by train/test overlap introduced during bootstrapping.",
  "(NORMAL vs CCDS) 동일 조건의 leak-free cross-validation에서 성능이 Accuracy 0.7699로 감소하는 것을 확인했습니다.": "(NORMAL vs CCDS) Under otherwise identical conditions, leak-free cross-validation reduced accuracy to 0.7699.",
  "(MCI vs SCI) 두 군을 구분하기 어려운 기존 biomarker의 한계를 분석하고, age를 regress out하는 방식으로 Accuracy 0.61 → 0.77, F1 0.48 → 0.77로 개선했습니다.": "(MCI vs SCI) Analyzed the limitations of existing biomarkers in distinguishing the two groups. Regressing out age improved accuracy from 0.61 to 0.77 and F1 from 0.48 to 0.77.",
  "NORMAL vs CCDS와 MCI vs SCI 접근을 결합한 SPECTRUM 모델을 설계하고 기존 방식과 비교했습니다.": "Designed SPECTRUM, combining NORMAL vs CCDS and MCI vs SCI approaches, and compared it with existing methods.",
  "혈액 biomarker 기반 데이터 분석 및 머신러닝 적용": "Analyze blood biomarker data and apply machine learning",
  "임상 데이터 특성과 실제 진단 보조 사용 맥락을 고려한 모델 개발": "Develop models with clinical data characteristics and diagnostic support workflows in mind",
  "기존 관련 연구를 기반으로 재현·확장": "Reproduce and extend prior research",
  "42마리 개의 350개 임상 영상과 VLM 기반 임상 특징을 이용한 발작 감지 연구입니다. 모델 성능뿐 아니라 데이터 편향, baseline, 실제 임상 적용 시나리오를 함께 검증하고 있습니다.": "Seizure detection research using 350 clinical videos from 42 dogs and VLM-based clinical features. Evaluation covers model performance, data bias, baselines, and practical clinical use cases.",
  "2차 진료 동물병원 입원환자 관리업무 전산화의 가능성과 한계": "Opportunities and limitations of digitizing inpatient care in veterinary referral hospitals",
  "동일한 입원 전산 시스템을 사용하는 5개 2차 진료 동물병원의 수의사와 테크니션을 대상으로 전산화의 적합성, 효율 변화, 불편 경험을 분석했습니다.": "Surveyed veterinarians and technicians at five referral hospitals using the same inpatient system to assess suitability for digitization, changes in efficiency, and usability issues.",
  "총 응답자 118명: 수의사 67명, 테크니션 51명": "118 respondents: 67 veterinarians and 51 technicians",
  "치료 지시·완료 확인과 일일 관찰 기록은 전산화 적합성이 높게 평가": "Treatment orders, completion tracking, and daily observation records were rated well suited to digitization",
  "인계, 환자 우선순위 결정, 경직된 입력 필드와 시스템 안정성은 주요 한계로 확인": "Key limitations included handoffs, patient prioritization, rigid input fields, and system stability",
  "연령이라는 교란 변수가 Alzheimer’s disease 음성 분류 성능에 미치는 영향을 분석한 연구입니다. npj digital medicine에 제출 예정입니다.": "Research on how age as a confounding variable affects speech-based Alzheimer’s disease classification. Submission to npj Digital Medicine is planned.",
  "굽이진 colon의 길이를 이미지에서 보다 일관되게 측정하기 위해 만든 컴퓨터비전 도구입니다.": "A computer vision tool for more consistent measurement of curved colon length from images.",
  "Segment Anything Model 활용": "Built with the Segment Anything Model",
  "굽은 구조의 segmentation 및 길이 산출": "Segment curved structures and calculate their length",
  "반복적인 수작업 측정 자동화": "Automate repetitive manual measurements",
  "연구 과정에서 ELISA kit 탐색과 비교 작업을 줄이기 위해 만든 소형 도구입니다.": "A small research tool that reduces the work of finding and comparing ELISA kits.",
  "냠코치": "Nyam Coach",
  "2025.05 ~ 2025.07 | Android Developer": "May – Jul 2025 | Android Developer",
  "식단 관리 플랫폼의 Android 개발 팀원으로 참여했습니다.": "Worked on the Android development team for a meal-planning platform.",
  "주요 화면 및 사용자 interaction 구현": "Implemented key screens and user interactions",
  "모바일 앱 협업 개발 경험": "Collaborated on mobile app development",
  "VetU1 · Vision AI / Software Developer · 2026.01 합류 · 2026.07 정규직 전환": "VetU1 · Vision AI / Software Developer · Joined Jan 2026 · Transitioned to full-time Jul 2026",
  "건국대학교 학부연구생 · 2026.01 ~": "Konkuk University · Undergraduate Researcher · Jan 2026 – present",
  "건국대학교 RISE 사업단 프로젝트팀 · Lead Developer · 2025.06 ~ 2025.11": "Konkuk University RISE Project Team · Lead Developer · Jun – Nov 2025",
  "Hult Prize · Campus Director · 2025.08 ~ 2026.02": "Hult Prize · Campus Director · Aug 2025 – Feb 2026",
  "건국대학교 영자신문 · 대외협력부장": "Konkuk University English Newspaper · Head of External Relations",
  "2026 · 서울청년기획봉사단 3기 · 유해식물 카드게임 제작 참여": "2026 · Seoul Youth Planning Volunteer Group · Cohort 3 · Helped create a card game about harmful plants",
  "Try Everything Global Student Startup IR Pitching Day · 대상(서울시장상)": "Try Everything Global Student Startup IR Pitching Day · Grand Prize (Seoul Mayor’s Award)",
  "Lunit · OpenAI Conquer Health · 2위": "Lunit · OpenAI Conquer Health · 2nd Place",
  "UNIV Startup Ideathon · 1위": "UNIV Startup Ideathon · 1st Place",
  "AI Rookie 100팀 → 40팀 → 진행 중 · 팀장": "AI Rookie · 100 teams → 40 teams → Ongoing · Team Lead",
  "학생 창업유망팀 300+ · 최종 선발": "Promising Student Startup Teams 300+ · Final Selection",
  "예비창업패키지 · VetU1 · CTO로 참여 · 1·2차 선정 · 1차 지원금 2,000만 원 · 2차 약 4,000만 원": "Pre-Startup Package · VetU1 · Participating as CTO · Selected for Phases 1 & 2 · Phase 1 funding: KRW 20M · Phase 2: approx. KRW 40M",
};

export default english;
